### PR TITLE
Allow to append location fixtures

### PR DESCRIPTION
**Pull request by chivy-we**
run `php bin/console doctrine:fixtures:load --append --group=location`

### CODE REVIEW

**Comment by chivy-we** [comment]
@bamoure What would we do if we want to run `php bin/console doctrine:fixtures:load --append --group=location` one time in the deployment?

**Comment by bamoure** [comment]
Do you mean on the production (or dev) server? I can run the command once from the server to add the locations.

**Comment by chivy-we** [comment]
Yes, I mean both dev and production. I appreciate it if you can run it after merging this pull request.

**Comment by bamoure** [comment]
Your team should be the one to do the merge requests, just let me know when it is done and I will run the command on all servers.

**Comment by chivy-we** [comment]
@bamoure yes, I just got the permission to merge it :)
May you help to run it on the Dev server (https://demo.humansis.org) first?

**Comment by bamoure** [comment]
Ran the command on the test server

**Comment by bamoure** [comment]
The test server is at https://front-test.bmstaging.info/ you can test to ensure it's working properly
Demo is the demo server, synced with master and the production server

**Comment by chivy-we** [comment]
It is working on the Testing server. And who can update this changes into master branch?

**Comment by bamoure** [comment]
I can do it. I'll do it as soon as possible and let you know when it is done for prod and demo.

**Comment by bamoure** [comment]
Merged on master, and fixtures loaded! 👍

**Pull request merged**
